import { afterEach,beforeEach,describe,expect,it,vi } from 'vitest';
import { mkdirSync,mkdtempSync,rmSync,writeFileSync,readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';

const prior=process.env.ADELIC_MEMORY_DATA_DIR;
const scope={workspace:'w',project:'p'};
let dir:string, statusData:string, notes:Map<string,any>, calls:any[], behavior:(name:string,args:any)=>any, writeSchema:any, mutateDuringStatus:(()=>void)|undefined;
const key=(s:any,p:string)=>`${s.workspace}/${s.project}/${p}`;
function addCatalog(path:string){const db=new DatabaseSync(join(dir,'db/memory.sqlite'));db.prepare('INSERT INTO pages VALUES(?,?,?,?,?,?,?)').run(Buffer.from('00000000000000000000000000000001','hex'),Buffer.from('00000000000000000000000000000011','hex'),path,path,1,null,Date.now()*1000);db.close();}
const uuid=(n:number)=>`00000000-0000-0000-0000-${n.toString(16).padStart(12,'0')}`;
function diskPath(path:string){return join(dir,'wiki',uuid(1),uuid(17),path);}
function addDisk(path:string,body:string,fm:Record<string,unknown>={}){const target=diskPath(path);mkdirSync(join(target,'..'),{recursive:true});const front=Object.keys(fm).length?`---\n${Object.entries(fm).map(([k,v])=>`${k}: ${JSON.stringify(v)}`).join('\n')}\n---\n`:'';writeFileSync(target,front+body);}
function response(req:any,result:any,error?:any,status=200){return new Response(JSON.stringify({jsonrpc:'2.0',id:req.id,...(error?{error}:{result})}),{status,headers:{'content-type':'application/json'}});}
beforeEach(async()=>{
 vi.resetModules(); dir=mkdtempSync(join(process.env.TMPDIR||tmpdir(),'adelic-mcp-'));statusData=dir;mkdirSync(join(dir,'db'));process.env.ADELIC_MEMORY_DATA_DIR=dir;
 const db=new DatabaseSync(join(dir,'db/memory.sqlite'));db.exec("CREATE TABLE workspaces(id BLOB PRIMARY KEY,name TEXT);CREATE TABLE projects(id BLOB PRIMARY KEY,workspace_id BLOB,name TEXT);CREATE TABLE pages(workspace_id BLOB,project_id BLOB,path TEXT,title TEXT,is_latest INTEGER,expires_at INTEGER,updated_at INTEGER);INSERT INTO workspaces VALUES(X'00000000000000000000000000000001','w');INSERT INTO projects VALUES(X'00000000000000000000000000000011',X'00000000000000000000000000000001','p');");db.close();
 mkdirSync(join(dir,'wiki',uuid(1),uuid(17)),{recursive:true});writeFileSync(join(dir,'wiki',uuid(1),'_meta.md'),'---\nworkspace: "w"\ntype: Scope Manifest\n---\n');writeFileSync(join(dir,'wiki',uuid(1),uuid(17),'_meta.md'),'---\nproject: "p"\ntype: Scope Manifest\n---\n');
 notes=new Map();calls=[];behavior=()=>undefined;mutateDuringStatus=undefined;writeSchema={workspace:{type:['string','null']},project:{type:['string','null']},path:{type:'string'},body:{type:'string'},pinned:{type:'boolean'},tier:{type:['string','null']},tags:{type:'array',items:{type:'string'}},expires_at:{type:['string','null']}};
 vi.stubGlobal('fetch',vi.fn(async(url:string,init:RequestInit)=>{if(url.endsWith('/admin/status')){mutateDuringStatus?.();return new Response(JSON.stringify({data_dir:statusData}),{status:200});}const req=JSON.parse(String(init.body));if(req.method==='initialize')return response(req,{});if(req.method==='tools/list')return response(req,{tools:[{name:'memory_query',inputSchema:{properties:{scopes:{},query:{},workspace:{},project:{}}}},{name:'memory_read_page',inputSchema:{properties:{workspace:{},project:{},path:{}}}},{name:'memory_write_page',inputSchema:{properties:writeSchema}}]});
  const {name,arguments:a}=req.params;calls.push({name,args:a});const special=behavior(name,a);if(special)return special(req);
  if(name==='memory_read_page'){let note=notes.get(key(a,a.path));try{const raw=readFileSync(diskPath(a.path),'utf8');const match=raw.match(/^---\n([\s\S]*?)\n---\n/);let fm:Record<string,unknown>={};if(match)for(const line of match[1].split('\n')){const m=line.match(/^([^:]+):\s*(.*)$/);if(m){try{fm[m[1]]=JSON.parse(m[2]);}catch{fm[m[1]]=m[2];}}}note={body:match?raw.slice(match[0].length):raw,frontmatter:fm};}catch{}if(!note)return response(req,null,{code:-32603,message:`page ${a.path} not found in resolved scope ${a.workspace}/${a.project}`});return response(req,{content:[{type:'text',text:JSON.stringify({...note,path:a.path,title:a.path})}]});}
  if(name==='memory_write_page'){expect(Object.keys(a).every((k:string)=>['body','expires_at','path','pinned','project','tags','tier','workspace'].includes(k))).toBe(true);expect(a.body).toEqual(expect.any(String));expect(a.body).not.toMatch(/^---/);for(const [field,type] of Object.entries({workspace:'string',project:'string',path:'string',pinned:'boolean',tier:'string'})){if(field in a)expect(typeof a[field]).toBe(type);}if('tags'in a)expect(Array.isArray(a.tags)&&a.tags.every((x:any)=>typeof x==='string')).toBe(true);if('expires_at'in a)expect(a.expires_at===null||typeof a.expires_at==='string'&&!Number.isNaN(Date.parse(a.expires_at))).toBe(true);notes.set(key(a,a.path),{body:a.body,frontmatter:Object.fromEntries(['pinned','tier','tags','expires_at'].filter(k=>k in a).map(k=>[k,a[k]]))});addDisk(a.path,a.body,notes.get(key(a,a.path)).frontmatter);addCatalog(a.path);return response(req,{content:[{type:'text',text:'{}'}]});}
  return response(req,{content:[{type:'text',text:'[]'}]});
 }));
});
afterEach(()=>{vi.unstubAllGlobals();if(prior===undefined)delete process.env.ADELIC_MEMORY_DATA_DIR;else process.env.ADELIC_MEMORY_DATA_DIR=prior;rmSync(dir,{recursive:true,force:true});});
const load=()=>import('../server/memory.js');
describe('ai-memory MCP persistence regressions',()=>{
 it('creates only on exact not-found; returns flattened arguments and readable saved note',async()=>{const m=await load();const saved=await m.sharedMemoryWrite(scope,'new.md','hello',null);expect(saved.body).toBe('hello');expect((await m.sharedMemoryRead(scope,'new.md') as any).frontmatter).toEqual({});expect(calls.filter(c=>c.name==='memory_write_page')).toHaveLength(1);});
 it.each(['workspace','project'])('rejects old write schema missing %s without writing',async(field)=>{delete writeSchema[field];const m=await load();await expect(m.sharedMemoryWrite(scope,'new.md','keep this body',null)).rejects.toThrow(new RegExp(`${field}.*string`));expect(calls.filter(c=>c.name==='memory_write_page')).toHaveLength(0);expect(notes.has(key(scope,'new.md'))).toBe(false);});
 it('rejects catalog-existing path for expected null without writing',async()=>{addCatalog('old.md');const m=await load();await expect(m.sharedMemoryWrite(scope,'old.md','x',null)).rejects.toMatchObject({status:409});expect(calls.some(c=>c.name==='memory_write_page')).toBe(false);});
 it.each([{label:'permission denied',reply:(req:any)=>response(req,null,{code:-32000,message:'permission denied'})},{label:'HTTP 503',reply:(req:any)=>response(req,{},undefined,503)}])('%s does not write even when catalog has no entry',async({reply})=>{behavior=(name)=>name==='memory_read_page'?reply:undefined;const m=await load();await expect(m.sharedMemoryWrite(scope,'absent.md','x',null)).rejects.toBeTruthy();expect(calls.some(c=>c.name==='memory_write_page')).toBe(false);});
 it('propagates unavailable catalog and does not write',async()=>{rmSync(join(dir,'db/memory.sqlite'));const m=await load();await expect(m.sharedMemoryWrite(scope,'missing.md','x',null)).rejects.toThrow(/Catálogo ai-memory indisponível/);expect(calls.some(c=>c.name==='memory_write_page')).toBe(false);});
 it('changes version when only metadata changes',async()=>{notes.set(key(scope,'meta.md'),{body:'same',frontmatter:{pinned:false,tier:'working',tags:['a'],expires_at:null,custom:{nested:true}}});addDisk('meta.md','same',notes.get(key(scope,'meta.md')).frontmatter);const m=await load();const before=await m.sharedMemoryRead(scope,'meta.md');notes.get(key(scope,'meta.md')).frontmatter.tags=['b'];addDisk('meta.md','same',notes.get(key(scope,'meta.md')).frontmatter);const after=await m.sharedMemoryRead(scope,'meta.md');expect(after.body).toBe(before.body);expect(after.version).not.toBe(before.version);expect(after.frontmatter).toHaveProperty('custom.nested',true);});
 it('serializes concurrent saves using same expected version: one success, one conflict, no MCP edit',async()=>{const fm={pinned:false,tier:'working',tags:[],expires_at:null};notes.set(key(scope,'race.md'),{body:'base',frontmatter:fm});addDisk('race.md','base',fm);const m=await load();const version=(await m.sharedMemoryRead(scope,'race.md')).version;const results=await Promise.allSettled([m.sharedMemoryWrite(scope,'race.md','one',version),m.sharedMemoryWrite(scope,'race.md','two',version)]);expect(results.filter(x=>x.status==='fulfilled')).toHaveLength(1);expect(results.filter(x=>x.status==='rejected').map((x:any)=>x.reason.status)).toEqual([409]);expect(calls.filter(c=>c.name==='memory_write_page')).toHaveLength(0);});
 it('blocks an existing-note edit on service/catalog root mismatch without MCP fallback',async()=>{notes.set(key(scope,'blocked.md'),{body:'base',frontmatter:{kind:'Fact'}});addDisk('blocked.md','base',{kind:'Fact'});const other=mkdtempSync(join(process.env.TMPDIR||tmpdir(),'other-memory-'));statusData=other;const m=await load();const version=(await m.sharedMemoryRead(scope,'blocked.md')).version;await expect(m.sharedMemoryWrite(scope,'blocked.md','changed',version)).rejects.toMatchObject({status:503});expect(readFileSync(diskPath('blocked.md'),'utf8')).toContain('base');expect(calls.filter(c=>c.name==='memory_write_page')).toHaveLength(0);rmSync(other,{recursive:true,force:true});});
 it('returns 503 for unavailable or incompatible /admin/status without MCP fallback',async()=>{notes.set(key(scope,'admin.md'),{body:'base',frontmatter:{kind:'Fact'}});addDisk('admin.md','base',{kind:'Fact'});const m=await load();const version=(await m.sharedMemoryRead(scope,'admin.md')).version;
   (fetch as any).mockImplementation(async(url:string,init:RequestInit)=>{if(url.endsWith('/admin/status'))return new Response('{}',{status:200});const req=JSON.parse(String(init.body));if(req.method==='tools/list')return response(req,{tools:[{name:'memory_read_page',inputSchema:{properties:{workspace:{},project:{},path:{}}}}]});return response(req,{content:[{type:'text',text:JSON.stringify({body:'base',frontmatter:{kind:'Fact'}})}]});});
   await expect(m.sharedMemoryWrite(scope,'admin.md','changed',version)).rejects.toMatchObject({status:503});expect(readFileSync(diskPath('admin.md'),'utf8')).toContain('base');expect(calls.filter(c=>c.name==='memory_write_page')).toHaveLength(0);
 });
 it('detects metadata-only changes after status fetch and preserves disk without fallback',async()=>{const fm={pinned:false,tier:'working',tags:['a'],custom:'original'};notes.set(key(scope,'metadata-race.md'),{body:'base',frontmatter:fm});addDisk('metadata-race.md','base',fm);const m=await load();const version=(await m.sharedMemoryRead(scope,'metadata-race.md')).version;
   mutateDuringStatus=()=>{const changed={...fm,custom:'changed'};notes.set(key(scope,'metadata-race.md'),{body:'base',frontmatter:changed});addDisk('metadata-race.md','base',changed);};
   await expect(m.sharedMemoryWrite(scope,'metadata-race.md','new body',version)).rejects.toMatchObject({status:409});expect(readFileSync(diskPath('metadata-race.md'),'utf8')).toContain('custom: "changed"');expect(readFileSync(diskPath('metadata-race.md'),'utf8')).toContain('base');expect(calls.filter(c=>c.name==='memory_write_page')).toHaveLength(0);
 });
 it('_global rejects before fetch for shared and legacy wrappers',async()=>{const m=await load();await expect(m.sharedMemoryWrite({workspace:'w',project:'_global'},'x.md','x',null)).rejects.toMatchObject({status:403});await expect(m.memoryWrite({memoryWorkspace:'w',memoryProject:'_global'} as any,'x.md','x')).rejects.toMatchObject({status:403});expect(fetch).not.toHaveBeenCalled();});
 it('legacy memoryWrite creates by MCP then edits local body preserving metadata',async()=>{notes.set(key(scope,'legacy.md'),{body:'existing',frontmatter:{pinned:true,tier:'working',tags:['safe'],expires_at:'2026-11-01T00:00:00Z',kind:'Fact',source:'test'}});addDisk('legacy.md','existing',notes.get(key(scope,'legacy.md')).frontmatter);const m=await load();const p:any={memoryWorkspace:'w',memoryProject:'p'};const created=await m.memoryWrite(p,'new-legacy.md','first');expect(created.body).toBe('first');const edit=await m.memoryWrite(p,'legacy.md','second');expect(edit.body).toBe('second');expect((edit as any).frontmatter).toEqual(notes.get(key(scope,'legacy.md')).frontmatter);expect(readFileSync(diskPath('legacy.md'),'utf8')).toContain('kind: "Fact"');expect(calls.filter(c=>c.name==='memory_write_page')).toHaveLength(1);});
});
