import { describe, expect, it } from 'vitest';
import type { ProviderInfo } from '../shared/contracts.js';
import { adaptEffort, capabilitiesReasoning, modelFor, supportsEffort, validReasoningEffort } from '../shared/reasoning.js';

const provider=(models:ProviderInfo['models'], reasoning=true, defaultModel?:string):ProviderInfo=>({id:'codex',name:'Provider',installed:true,available:true,status:'ready',detail:'test',models,defaultModel,capabilities:{fast:true,tools:true,approvals:true,cancel:true,reasoning}});
describe('shared reasoning capability helpers',()=>{
 it('requires an exact known model and prefers provider defaultModel to isDefault',()=>{const p=provider([{id:'first',name:'First',isDefault:true,efforts:['low']},{id:'preferred',name:'Preferred',efforts:['high']}],true,'preferred');expect(modelFor(p,'missing')).toBeUndefined();expect(modelFor(p)?.id).toBe('preferred');expect(modelFor(p,'first')?.id).toBe('first');});
 it('reports false for missing, empty, or explicitly disabled reasoning',()=>{expect(capabilitiesReasoning(provider([{id:'m',name:'M'}]))).toMatchObject({reasoning:false,efforts:undefined});expect(supportsEffort(provider([{id:'m',name:'M',efforts:[]}]),'m','low')).toBe(false);expect(capabilitiesReasoning(provider([{id:'m',name:'M',efforts:['low']}],false),'m').reasoning).toBe(false);expect(adaptEffort(provider([{id:'m',name:'M',efforts:['low']}],false),'m','low')).toBeUndefined();});
 it('dedupes and filters advertised identifiers including auto',()=>{const p=provider([{id:'m',name:'M',efforts:['ultra','ultra','auto','bad value','new-tier']}]);expect(capabilitiesReasoning(p,'m')).toEqual({reasoning:true,efforts:['ultra','new-tier']});expect(validReasoningEffort('new-tier')).toBe(true);});
 it('returns exact values and clamps to the nearest lower advertised level',()=>{const sol=provider([{id:'s',name:'Sol',efforts:['ultra','high','low']}]);const luna=provider([{id:'l',name:'Luna',efforts:['max','high','medium','low']}]);expect(adaptEffort(sol,'s','ultra')).toBe('ultra');expect(adaptEffort(luna,'l','ultra')).toBe('max');expect(adaptEffort(luna,'l','xhigh')).toBe('high');});
 it('uses low/high auto routing when announced, otherwise valid default then first capability',()=>{const p=provider([{id:'m',name:'M',efforts:['medium','high'],defaultReasoningEffort:'high'}]);expect(adaptEffort(p,'m','low')).toBe('medium');expect(adaptEffort(p,'m','high')).toBe('high');expect(adaptEffort(p,'m','unannounced')).toBe('high');});
 it('chooses the lowest advertised ranked effort above a request regardless of catalog order and preserves valid defaults for unknown levels',()=>{const p=provider([{id:'m',name:'M',efforts:['ultra','medium'],defaultReasoningEffort:'medium'}]);expect(adaptEffort(p,'m','minimal')).toBe('medium');expect(adaptEffort(p,'m','unknown')).toBe('medium');});
});
